default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV["ROR_RECIPE_APP_DATABASE_NAME"] %>
  username: <%= ENV["ROR_RECIPE_APP_DATABASE_USERNAME"] %>
  password: <%= ENV["ROR_RECIPE_APP_DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: <%= ENV["ROR_RECIPE_APP_DATABASE_NAME"] %>
  username: <%= ENV["ROR_RECIPE_APP_DATABASE_USERNAME"] %>
  password: <%= ENV["ROR_RECIPE_APP_DATABASE_PASSWORD"] %>

production:
  <<: *default
  database: <%= ENV["ROR_RECIPE_APP_DATABASE_NAME"] %>
  username: <%= ENV["ROR_RECIPE_APP_DATABASE_USERNAME"] %>
  password: <%= ENV["ROR_RECIPE_APP_DATABASE_PASSWORD"] %>
