default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Recipe_App_development
  username: <%= ENV["ROR_RECIPE_APP_DATABASE_USERNAME"] %>
  password: <%= ENV["ROR_RECIPE_APP_DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: Recipe_App_test
  username: <%= ENV["ROR_RECIPE_APP_DATABASE_USERNAME"] %>
  password: <%= ENV["ROR_RECIPE_APP_DATABASE_PASSWORD"] %>

production:
  <<: *default
  database: Recipe_App_production
  username: <%= ENV["ROR_RECIPE_APP_DATABASE_USERNAME"] %>
  password: <%= ENV["ROR_RECIPE_APP_DATABASE_PASSWORD"] %>
